// <auto-generated />
using System;
using FSA_3S.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FSA_3S.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250403034631_database")]
    partial class database
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FSA_3S.Models.Entities.AppointmentEntity", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("appointmentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address");

                    b.Property<DateOnly>("AppointmentDate")
                        .HasColumnType("date")
                        .HasColumnName("appointmentDate");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdat");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("createdBy");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedat");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updatedBy");

                    b.HasKey("AppointmentId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CustomerId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("appointment");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.AuditEntity", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("auditId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditId"));

                    b.Property<int?>("ContractId")
                        .HasColumnType("int")
                        .HasColumnName("contractId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("createdBy");

                    b.Property<string>("EntityType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("entityType");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.Property<int?>("RealEstateId")
                        .HasColumnType("int")
                        .HasColumnName("realEstateId");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updatedBy");

                    b.HasKey("AuditId");

                    b.HasIndex("ContractId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("RealEstateId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("audit");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.ClauseEntity", b =>
                {
                    b.Property<int>("ClauseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("clauseId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClauseId"));

                    b.Property<string>("ClauseContent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("clauseContent");

                    b.Property<int>("ClauseNumber")
                        .HasColumnType("int")
                        .HasColumnName("clauseNumber");

                    b.Property<int>("ClauseType")
                        .HasColumnType("int")
                        .HasColumnName("clauseType");

                    b.HasKey("ClauseId");

                    b.ToTable("clause");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.ContractEntity", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("contractId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractId"));

                    b.Property<string>("ContractStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contractstatus");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contracttype");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("createdBy");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("enddate");

                    b.Property<int?>("RealEstateId")
                        .HasColumnType("int")
                        .HasColumnName("realEstateId");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("startdate");

                    b.Property<int>("StatusPayment")
                        .HasColumnType("int")
                        .HasColumnName("statuspayment");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updatedBy");

                    b.HasKey("ContractId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("RealEstateId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("contract");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.CustomerEntity", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("customerId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("address");

                    b.Property<string>("CCCD")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CCCD");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdat");

                    b.Property<int>("CustomerType")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .HasColumnName("customertype");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fullname");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("gender");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("phonenumber");

                    b.HasKey("CustomerId");

                    b.ToTable("customer");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.MappingContractCustomerEntity", b =>
                {
                    b.Property<int>("MappingContractCustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mappingContractCustomerId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MappingContractCustomerId"));

                    b.Property<int?>("BuyerId")
                        .HasColumnType("int")
                        .HasColumnName("buyerId");

                    b.Property<int>("ContractId")
                        .HasColumnType("int")
                        .HasColumnName("contractId");

                    b.Property<int?>("SellerId")
                        .HasColumnType("int")
                        .HasColumnName("sellerId");

                    b.HasKey("MappingContractCustomerId");

                    b.HasIndex("BuyerId");

                    b.HasIndex("ContractId");

                    b.HasIndex("SellerId");

                    b.ToTable("mappingcontractcustomer");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.MappingUserAppointmentEntity", b =>
                {
                    b.Property<int>("MappingUserAppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mappingUserAppointmentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MappingUserAppointmentId"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("ApprovalStatus")
                        .HasMaxLength(20)
                        .HasColumnType("int")
                        .HasColumnName("approval");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("UserEntityUserId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("MappingUserAppointmentId");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UserEntityUserId");

                    b.HasIndex("UserId");

                    b.ToTable("mappinguserappointment");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.MappingUserNotificationEntity", b =>
                {
                    b.Property<int>("MappingUserNotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mappingUserNotificationId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MappingUserNotificationId"));

                    b.Property<int>("NotificationId")
                        .HasColumnType("int");

                    b.Property<int?>("UserEntityUserId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("MappingUserNotificationId");

                    b.HasIndex("NotificationId");

                    b.HasIndex("UserEntityUserId");

                    b.HasIndex("UserId");

                    b.ToTable("mappingusernotification");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.RealEstateEntity", b =>
                {
                    b.Property<int>("RealEstateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("realEstateId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RealEstateId"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("address");

                    b.Property<int>("ApprovalStatus")
                        .HasMaxLength(20)
                        .HasColumnType("int")
                        .HasColumnName("approval");

                    b.Property<decimal?>("Area")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("area");

                    b.Property<int?>("Bathrooms")
                        .HasColumnType("int")
                        .HasColumnName("bathrooms");

                    b.Property<int?>("Bedrooms")
                        .HasColumnType("int")
                        .HasColumnName("bedrooms");

                    b.Property<string>("Coordinate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("coordinates");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdat");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("createdBy");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("image_path");

                    b.Property<string>("IsFurnished")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("is_furnished");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("RealEstateName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("RealEstateStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("RealEstateType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("type");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("saledate");

                    b.Property<int>("Seller")
                        .HasColumnType("int")
                        .HasColumnName("sellerid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedat");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updatedBy");

                    b.HasKey("RealEstateId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Seller");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("realestate");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.ReportEntity", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("reportId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<int?>("NumberOfAppointments")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfContracts")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfRealEstates")
                        .HasColumnType("int");

                    b.HasKey("ReportId");

                    b.ToTable("report");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.UserEntity", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("birthdate");

                    b.Property<string>("CCCD")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("cccd");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDate");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fullname");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("gender");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("phonenumber");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("status");

                    b.Property<string>("TimeOfWork")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("timeofwork");

                    b.Property<string>("TypeOfStaff")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("typeofstaff");

                    b.HasKey("UserId");

                    b.ToTable("user");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.WorkEntity", b =>
                {
                    b.Property<int>("WorkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("work_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkId"));

                    b.Property<string>("Friday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FridayTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Monday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MondayTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Saturday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaturdayTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sunday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SundayTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thursday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThursdayTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tuesday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TuesdayTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserEntityUserId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.Property<string>("Wednesday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WednesdayTime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorkId");

                    b.HasIndex("UserEntityUserId");

                    b.ToTable("work");
                });

            modelBuilder.Entity("FSA_3S.Models.NotificationEntity", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdNotification");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsRead");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Message");

                    b.Property<int?>("ReceiverId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("ReceiverId");

                    b.Property<int?>("SenderId")
                        .HasColumnType("int")
                        .HasColumnName("SenderId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Title");

                    b.HasKey("NotificationId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("MappingContractClauseEntity", b =>
                {
                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<int>("ClauseId")
                        .HasColumnType("int");

                    b.HasKey("ContractId", "ClauseId");

                    b.HasIndex("ClauseId");

                    b.ToTable("mappingcontractclause");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.AppointmentEntity", b =>
                {
                    b.HasOne("FSA_3S.Models.Entities.UserEntity", "Creator")
                        .WithMany("AppointmentsCreated")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FSA_3S.Models.Entities.CustomerEntity", "Customer")
                        .WithMany("Appointments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FSA_3S.Models.Entities.UserEntity", "Updater")
                        .WithMany("AppointmentsUpdated")
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("Creator");

                    b.Navigation("Customer");

                    b.Navigation("Updater");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.AuditEntity", b =>
                {
                    b.HasOne("FSA_3S.Models.Entities.ContractEntity", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId");

                    b.HasOne("FSA_3S.Models.Entities.UserEntity", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("FSA_3S.Models.Entities.RealEstateEntity", "RealEstate")
                        .WithMany("Audits")
                        .HasForeignKey("RealEstateId");

                    b.HasOne("FSA_3S.Models.Entities.UserEntity", "Updater")
                        .WithMany()
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("Contract");

                    b.Navigation("Creator");

                    b.Navigation("RealEstate");

                    b.Navigation("Updater");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.ContractEntity", b =>
                {
                    b.HasOne("FSA_3S.Models.Entities.UserEntity", "Creator")
                        .WithMany("ContractsCreated")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FSA_3S.Models.Entities.RealEstateEntity", "RealEstate")
                        .WithMany("Contracts")
                        .HasForeignKey("RealEstateId");

                    b.HasOne("FSA_3S.Models.Entities.UserEntity", "Updater")
                        .WithMany("ContractsUpdated")
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("Creator");

                    b.Navigation("RealEstate");

                    b.Navigation("Updater");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.MappingContractCustomerEntity", b =>
                {
                    b.HasOne("FSA_3S.Models.Entities.CustomerEntity", "Buyer")
                        .WithMany("BuyerMappings")
                        .HasForeignKey("BuyerId");

                    b.HasOne("FSA_3S.Models.Entities.ContractEntity", "Contract")
                        .WithMany("MappingContractCustomer")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FSA_3S.Models.Entities.CustomerEntity", "Seller")
                        .WithMany("SellerMappings")
                        .HasForeignKey("SellerId");

                    b.Navigation("Buyer");

                    b.Navigation("Contract");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.MappingUserAppointmentEntity", b =>
                {
                    b.HasOne("FSA_3S.Models.Entities.AppointmentEntity", "Appointment")
                        .WithMany("MappingUserAppointments")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FSA_3S.Models.Entities.UserEntity", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FSA_3S.Models.Entities.UserEntity", "Updater")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FSA_3S.Models.Entities.UserEntity", null)
                        .WithMany("MappingUserAppointments")
                        .HasForeignKey("UserEntityUserId");

                    b.HasOne("FSA_3S.Models.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Creator");

                    b.Navigation("Updater");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.MappingUserNotificationEntity", b =>
                {
                    b.HasOne("FSA_3S.Models.NotificationEntity", "Notification")
                        .WithMany()
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FSA_3S.Models.Entities.UserEntity", null)
                        .WithMany("MappingUserNotifications")
                        .HasForeignKey("UserEntityUserId");

                    b.HasOne("FSA_3S.Models.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.RealEstateEntity", b =>
                {
                    b.HasOne("FSA_3S.Models.Entities.UserEntity", "Creator")
                        .WithMany("RealEstatesCreated")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FSA_3S.Models.Entities.CustomerEntity", "Customer")
                        .WithMany("RealEstates")
                        .HasForeignKey("Seller")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FSA_3S.Models.Entities.UserEntity", "Updater")
                        .WithMany("RealEstatesUpdated")
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("Creator");

                    b.Navigation("Customer");

                    b.Navigation("Updater");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.WorkEntity", b =>
                {
                    b.HasOne("FSA_3S.Models.Entities.UserEntity", null)
                        .WithMany("Works")
                        .HasForeignKey("UserEntityUserId");
                });

            modelBuilder.Entity("FSA_3S.Models.NotificationEntity", b =>
                {
                    b.HasOne("FSA_3S.Models.Entities.UserEntity", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FSA_3S.Models.Entities.UserEntity", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("MappingContractClauseEntity", b =>
                {
                    b.HasOne("FSA_3S.Models.Entities.ClauseEntity", "Clause")
                        .WithMany("ContractClauses")
                        .HasForeignKey("ClauseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FSA_3S.Models.Entities.ContractEntity", "Contract")
                        .WithMany("ContractClauses")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clause");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.AppointmentEntity", b =>
                {
                    b.Navigation("MappingUserAppointments");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.ClauseEntity", b =>
                {
                    b.Navigation("ContractClauses");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.ContractEntity", b =>
                {
                    b.Navigation("ContractClauses");

                    b.Navigation("MappingContractCustomer");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.CustomerEntity", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("BuyerMappings");

                    b.Navigation("RealEstates");

                    b.Navigation("SellerMappings");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.RealEstateEntity", b =>
                {
                    b.Navigation("Audits");

                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.UserEntity", b =>
                {
                    b.Navigation("AppointmentsCreated");

                    b.Navigation("AppointmentsUpdated");

                    b.Navigation("ContractsCreated");

                    b.Navigation("ContractsUpdated");

                    b.Navigation("MappingUserAppointments");

                    b.Navigation("MappingUserNotifications");

                    b.Navigation("RealEstatesCreated");

                    b.Navigation("RealEstatesUpdated");

                    b.Navigation("Works");
                });
#pragma warning restore 612, 618
        }
    }
}
